name: CI/CD

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
  schedule:
    - cron: '15 12 * * 4'

jobs:
  eslint:
    name: Run ESLint and Prettier
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install eslint@8.10.0 --save-dev --save-exact prettier

      - name: Run ESLint and Prettier
        run: |
          npx eslint .
            --config .eslintrc.js
            --ext .js,.jsx,.ts,.tsx
            --fix
          npx prettier --write .

  deploy:
    name: Deploy to Vercel
    runs-on: ubuntu-latest
    needs: eslint
    if: success('eslint')
    steps:
      - name: Deploy to Vercel
        run: npx vercel --token ${{ secrets.VERCEL_TOKEN }} --prod
