name: ESLint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '15 12 * * 4'

jobs:
  eslint:
    name: Run ESLint scanning
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install ESLint and Prettier
        run: |
          npm install eslint@8.10.0 --force
          npm install prettier@3.0.0
          npm install eslint-plugin-prettier@latest

      - name: Run ESLint with Prettier formatter
        run: |
          npx eslint .
            --config .eslintrc.js
            --ext .js,.jsx,.ts,.tsx
            --format node_modules/eslint-formatter-prettier
          npx prettier --check .
